# deployment/feature-extractor.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-extractor
  namespace: autoshield-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feature-extractor
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumclusterwidenetworkpolicies", "ciliumnetworkpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: feature-extractor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: feature-extractor
subjects:
- kind: ServiceAccount
  name: feature-extractor
  namespace: autoshield-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extractor
  namespace: autoshield-system
  labels:
    app: autoshield
    component: feature-extractor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoshield
      component: feature-extractor
  template:
    metadata:
      labels:
        app: autoshield
        component: feature-extractor
    spec:
      serviceAccountName: feature-extractor
      containers:
      - name: feature-extractor
        image: autoshield/feature-extractor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
          readOnly: true
        - name: flow-storage
          mountPath: /data
      volumes:
      - name: kubeconfig
        configMap:
          name: kube-config
      - name: flow-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: feature-extractor
  namespace: autoshield-system
spec:
  selector:
    app: autoshield
    component: feature-extractor
  ports:
  - port: 8080
    targetPort: 8080
    name: http