# deployment/inference-service.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-service
  namespace: autoshield-system
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: autoshield-system
  labels:
    app: autoshield
    component: inference
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: autoshield
    component: inference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
  namespace: autoshield-system
  labels:
    app: autoshield
    component: inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoshield
      component: inference
  template:
    metadata:
      labels:
        app: autoshield
        component: inference
    spec:
      serviceAccountName: inference-service
      containers:
      - name: inference-service
        image: autoshield/inference:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: USE_GPU
          value: "false"  # Set to "true" if GPU nodes available
        - name: MODEL_PATH
          value: "/app/data/models/cnn-lstm/latest/final_model.pth"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: model-storage
          mountPath: /app/data/models
          readOnly: true
      volumes:
      - name: model-storage
        configMap:
          name: model-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config
  namespace: autoshield-system
data:
  # In production, models would be stored in object storage
  # and downloaded on startup
  model-path: "/app/data/models/cnn-lstm"