# deployment/inference-service.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-service
  namespace: autoshield-system
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: autoshield-system
  labels:
    app: autoshield
    component: inference
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: autoshield
    component: inference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
  namespace: autoshield-system
  labels:
    app: autoshield
    component: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoshield
      component: inference
  template:
    metadata:
      labels:
        app: autoshield
        component: inference
    spec:
      serviceAccountName: inference-service
      containers:
      - name: inference-service
        image: autoshield/inference:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: USE_GPU
          value: "false"  # Set to "true" if GPU nodes available
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10